name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --dev --no-install-project
      - uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v2
      - run: just deps
      - run: uv sync --dev
      - run: uv run python setup.py build_ext --inplace
      - run: uv run pytest
